### PR TITLE
OutputFileLog.path container path bug fix

### LINKED ISSUE #290: Output Log Path using host paths
Looking at the `logs.outputs.path` it looks like the path from the host VM is being recorded, rather then the docker container path. Thus it looks like `/mnt/funnel/b7to4ir3qt7gv3763k7g/var/run/cwl/gaf.json`

Example
```
"logs" : [
      {
         "outputs" : [
            {
               "path" : "/mnt/funnel/b7to4ir3qt7gv3763k7g/var/run/cwl/gaf.json",
               "size_bytes" : "70989749",
               "url" : "swift://biostream/job1/output/gaf.json"
            }
         ],
         "logs" : [
            {
               "host_ip" : "10.50.50.55",
               "start_time" : "2017-11-02T20:38:46.032906942Z",
               "end_time" : "2017-11-02T20:39:28.485524782Z"
            }
         ],
         "end_time" : "2017-11-02T20:39:30.815287726Z",
         "start_time" : "2017-11-02T20:38:44.187495026Z"
      }
   ],
```

### PR DESCRIPTION
**Pull request by adamstruck**
- deduplicated storage code for put
- report container paths in OutputFileLog

closes #290

### CODE REVIEW

File: storage/storage.go [hunk 1]
```diff
@@ -61,7 +63,43 @@ func (storage Storage) Put(ctx context.Context, url string, path string, class t
...
+			Url:       url,
+			Path:      path,
+			SizeBytes: fileSize(path),
+		})
+	case Directory:
+		var files []hostfile
+		files, err = walkFiles(path)
+
+		for _, f := range files {
+			u := strings.TrimSuffix(url, "/") + "/" + f.rel
```
Comment (buchanae) [inline storage/storage.go]: We lost something here. The local backend was using `path.Join`.

Comment (adamstruck) [reply storage/storage.go]: This ends up being equivalent.

Comment (buchanae) [reply storage/storage.go]: It's not equivalent for windows.

Comment (adamstruck) [reply storage/storage.go]: I don't think we have windows support anyways

Comment (buchanae) [reply storage/storage.go]: We don't need to be making it more difficult by handling file paths the wrong way.

Comment (adamstruck) [reply storage/storage.go]: technically its a file URL at this point. According to https://en.wikipedia.org/wiki/File_URI_scheme this would still work for windows

Comment (buchanae) [reply storage/storage.go]: I can live with that
