### PR TITLE
storage: bug fixes

### LINKED ISSUE #459: storage/swift: panic
screen shot 2018-01-25 at 5 34 07 pm

### PR DESCRIPTION
**Pull request by adamstruck**
* fixed url parsing panic; closes #459 
* fixed directory download bug that prevented recursive downloads of subdirectories
* better error reporting for SupportsGet/SupportsPut calls

### CODE REVIEW

File: storage/local.go [hunk 1]
```diff
@@ -14,6 +14,7 @@ import (
 
 // LocalBackend provides access to a local-disk storage system.
 type LocalBackend struct {
+	Name        string
```
Comment (buchanae) [inline storage/local.go]: Are these accidentally left over? Same for HTTP

**Comment by buchanae** [comment]
Just the one question, otherwise looks good
