### PR TITLE
compute: cancel queued tasks; log failed Compute.Submit calls

### LINKED ISSUE #28: Watch for jobs that never start
Possibly closely related to #25

### LINKED ISSUE #118: Report when jobs cannot be scheduled on HTCondor, Slurm, etc.
It's tricky to know when a job isn't starting on HTCondor because it doesn't match any workers. You really have to know a lot about administering both a Funnel cluster and an HTCondor cluster. You need to find the Funnel logs and know about `condor_q -analyze`

There's probably something nice we can do to report scheduling information from HTCondor

### LINKED ISSUE #327: compute: handle cancel in batch/HPC
@adamstruck Does AWS Batch and HPC handle canceling a queued task?

### PR DESCRIPTION
**Pull request by adamstruck**
Cancel queued tasks in AWS Batch, HTCondor, Slurm, etc.

closes #327

### CODE REVIEW

**Comment by adamstruck** [comment]
This PR also covers creating system log events when the Compute.Submit method fails.

File: compute/batch/backend.go [hunk 1]
```diff
@@ -68,10 +79,52 @@ func (b *Backend) Submit(task *tes.Task) error {
...
+
+	return b.event.WriteEvent(
+		ctx, events.NewMetadata(task.Id, 0, map[string]string{"awsbatch_id": *resp.JobId}),
+	)
+}
+
+// Cancel removes tasks from the AWS batch job queue.
+func (b *Backend) Cancel(ctx context.Context, taskID string) error {
+	var task *tes.Task
+	var err error
```
Comment (buchanae) [inline compute/batch/backend.go]: nit: these seem unnecessary. the `x := Y()` pattern is the best option.

File: compute/batch/backend.go [hunk 2]
```diff
@@ -68,10 +79,52 @@ func (b *Backend) Submit(task *tes.Task) error {
...
+
+	task, err = b.database.GetTask(
+		ctx, &tes.GetTaskRequest{Id: taskID, View: tes.TaskView_FULL},
```
Comment (buchanae) [inline compute/batch/backend.go]: Probably want the basic view.

File: compute/batch/backend.go [hunk 3]
```diff
@@ -68,10 +79,52 @@ func (b *Backend) Submit(task *tes.Task) error {
...
+		return err
+	}
+
+	// only cancel tasks in a QUEUED state
+	state := task.GetState()
+	if state != tes.State_QUEUED {
+		return nil
+	}
+
+	backendID := getAWSTaskID(task)
```
Comment (buchanae) [inline compute/batch/backend.go]: There's a small chance that the batch ID isn't there. Probably want to handle that case.

File: compute/hpc_backend.go [hunk 4]
```diff
@@ -14,45 +15,95 @@ import (
...
+	)
+}
+
+// Cancel cancels a task via "qdel", "condor_rm", "scancel", etc.
+func (b *HPCBackend) Cancel(ctx context.Context, taskID string) error {
+	var task *tes.Task
+	var err error
+
+	task, err = b.Database.GetTask(
+		ctx, &tes.GetTaskRequest{Id: taskID, View: tes.TaskView_FULL},
```
Comment (buchanae) [inline compute/hpc_backend.go]: Basic view here too?

File: compute/hpc_backend.go [hunk 5]
```diff
@@ -14,45 +15,95 @@ import (
...
+	return b.Event.WriteEvent(
+		ctx,
+		events.NewMetadata(task.Id, 0, map[string]string{fmt.Sprintf("%s_id", b.Name): backendID}),
+	)
+}
+
+// Cancel cancels a task via "qdel", "condor_rm", "scancel", etc.
+func (b *HPCBackend) Cancel(ctx context.Context, taskID string) error {
+	var task *tes.Task
+	var err error
```
Comment (buchanae) [inline compute/hpc_backend.go]: same pattern as above

File: compute/hpc_backend.go [hunk 6]
```diff
@@ -14,45 +15,95 @@ import (
...
+
+	task, err = b.Database.GetTask(
+		ctx, &tes.GetTaskRequest{Id: taskID, View: tes.TaskView_FULL},
+	)
+	if err != nil {
+		return err
+	}
+
+	// only cancel tasks in a QUEUED state
+	state := task.GetState()
```
Comment (buchanae) [inline compute/hpc_backend.go]: GetState isn't necessary, since State is an int value. `if task.State != tes.Queued` would do.

File: compute/hpc_backend.go [hunk 7]
```diff
@@ -14,45 +15,95 @@ import (
...
+	if state != tes.State_QUEUED {
+		return nil
+	}
+
+	backendID := getBackendTaskID(task, b.Name)
+	if backendID != "" {
```
Comment (buchanae) [inline compute/hpc_backend.go]: Looks like you handle the missing ID here, just need to make Batch match.

File: compute/hpc_backend.go [hunk 8]
```diff
@@ -14,45 +15,95 @@ import (
...
+		cmd := exec.Command(b.CancelCmd, backendID)
+		return cmd.Run()
+	}
+
+	return fmt.Errorf("failed to get %s_id for task %s", b.Name, taskID)
```
Comment (buchanae) [inline compute/hpc_backend.go]: nit: the pattern I like is that exceptional conditions, such as an empty ID, are handled in the body of the if-statement, and the regular flow stays at the root level. The code here is the opposite.
